### ISSUE TITLE
Handle git bash for windows (on msys1)

### ISSUE THREAD

**Issue by techalchemy** [sarugaku/shellingham#1]
The real question is can we even spawn processes using this?

**Comment by uranusjr** [comment]
There is another complication to this problem: How do you install Python in Git Bash? Msys, or Win32 native? The Win32 native Python can work correctly in Git Bash (it is just another Window program), and detects bash.exe correctly. But I don’t even know how to install Python in Msys…

**Comment by uranusjr** [comment]
![mingw64__c_users_uranusjr_documents_programming_shellingham 19_06_18 22_39_56](https://user-images.githubusercontent.com/605277/41604403-bc3f6822-7411-11e8-849b-49584b955763.png)

**Comment by techalchemy** [comment]
Nice. You install python the same way as anything. `pacman -Syu python`.

**Comment by uranusjr** [comment]
Seems like they removed pacman intentionally: https://github.com/git-for-windows/git/issues/397#issuecomment-140984199

I’ll leave this unsupported. If someone is really so determined to use it they can raise this.
