### ISSUE TITLE
Revise encoding handling on Windows

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/shellingham#16]
From pypa/pipenv#3382. Need to do something similar to #10: Try system encoding, ~and then utf-8,~ and replace unparsables.

Edit: No we don’t want to try UTF-8.

**Comment by techalchemy** [comment]
@uranusjr I literally just finished handling this problem I think I mentioned it in slack

**Comment by techalchemy** [comment]
Let me read your thing and follow up
