### ISSUE TITLE
Try system shell if detection fails

### ISSUE THREAD

**Issue by D3f0** [sarugaku/shellingham#18]
I'm currently using poetry (a tool similar to pipenv, but based on pyproject.toml), for building a python project. This tool relies on shellingham to detect the running shell and launch them in its virtual environments.
Running the command `poetry shell` as a task in Visual Studio Code, like this:
```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "poetry shell",
            "type": "shell",
            "command": "poetry shell",
            "problemMatcher": []
        }
    ]

}

```
produces the following outcome:
```shell
> Executing task: poetry shell <

Spawning shell within /Users/nahuel/Library/Caches/pypoetry/virtualenvs/testproject-py3.6

[RuntimeError]
Unable to detect the current shell.

shell

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Would it be possible to use the $SHELL variable if there's no process in the tree with a usable shell name?

**Comment by glehmann** [comment]
that looks like a reasonable default to me. Also note that it would help with some rare cases on linux as well — for example when running a command using shellingham on a remote host without going into the shell first

```bash
glehmann@laptop:~$ ssh server 'python -c "import shellingham; print(shellingham.detect_shell())"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/glehmann/.local/lib/python2.7/site-packages/shellingham/__init__.py", line 25, in detect_shell
    raise ShellDetectionFailure()
shellingham._core.ShellDetectionFailure
glehmann@laptop:~$ ssh server 'python -c "import os; print(os.environ[\'SHELL\'])"'
/bin/bash
glehmann@laptop:~$ ssh server ps
  PID TTY          TIME CMD
63893 ?        00:00:00 sshd
63894 ?        00:00:00 ps
glehmann@laptop:~$ ssh server
glehmann@server:~$ python -c "import shellingham; print(shellingham.detect_shell())"
('bash', '/bin/bash')
```

**Comment by uranusjr** [comment]
The original intention of this behaviour is to let the callee perform whatever fallback necessary if this happens. Shellingham detects the current inner-most shell, and I feel an exception is appropriate if it cannot detect one.

Maybe a `default` kwarg is an acceptable solution? Like built-in `dict[]` vs `dict.get()`, you can provide a default value to fallback to if detection fails, so you can write something like

```
import os, shellingham; print(shellingham.detect_shell(default=os.environ['SHELL'])`
```

**Comment by uranusjr** [comment]
I’m leaving this for the application implementers for now. See notes in README for my personal recommendations. (/cc @sdispater)

**Comment by D3f0** [comment]
Seems fair to me. Thank you!
