### ISSUE TITLE
Please add ash

### ISSUE THREAD

**Issue by Congee** [sarugaku/shellingham#19]
FYI, I am using poetry in the alpine docker distribution, whose default shell is ash. poetry is unable to run some commands since it relies on shellingham. Please add ash to this set. :-P

https://github.com/sarugaku/shellingham/blob/a5128efe96a26c2e46a0ae50ab54e2fbf47099b2/src/shellingham/_core.py#L1-L11

**Comment by uranusjr** [comment]
Pull request welcomed!
