### ISSUE TITLE
setup.py is missing in the tar.gz archive

### ISSUE THREAD

**Issue by tuxmaster5000** [sarugaku/shellingham#33]
The file is missing, but needed to build an rpm package.

**Comment by uranusjr** [comment]
Would it be possible if you add a step to your build system to supply `setup.py` yourself? I am a bit uncomfortable to supply `setup.py` for this reason, since I will be stuck supporting a platform I don’t use.

**Comment by tuxmaster5000** [comment]
In the git repo I see the file.
It is needed, because without it, an chicken/egg problem will result.
poetry needs shellingham to build it. But to build shellingham poetry is needed.

**Comment by uranusjr** [comment]
Uh, no you don’t. I don’t use Poetry to build Shellingham myself either. You can use pip to either install or produce a wheel for Shellingham.

**Comment by tuxmaster5000** [comment]
I have simply create an new tar archive from you last release and add the last setup.py from yout git. Then all will work. I don't know, why the file is in the git, but missing in the release tar.

**Comment by eli-schwartz** [comment]
I have no idea what this poetry nonsense is about, but it is true that the latest tagged release doesn't support building with plain old setuptools. You need some frontend like pip, or indeed poetry.

It's not really that big of a deal -- 8536885ee8d38d79cfd53afd244da57abffde9b8 re-added a simple setup.py which runs:

```
from setuptools import setup
setup()
```

And that's sufficient to run `python setup.py install`.

> The file is missing, but needed to build an rpm package.

Right, for distro packaging (this is my situation too) we need to use setuptools, and we don't generally use wheels either as that just adds additional container requirements for no good reason (and complicates the bootstrap graph).

**Comment by uranusjr** [comment]
I asked Red Hat folks, and was pointed to a new tool that aims to replace direct `setup.py` invocation. [I have created a thread on discuss.python.org](https://discuss.python.org/t/tool-to-build-a-rpm-package-backed-by-pep-517/4020) as a canonical place for discussions related to this. Please feel free to raise any further problems you may have on this topic.
