### ISSUE TITLE
 treat cygwin like linux

### ISSUE THREAD

**Issue by badboybeyer** [sarugaku/shellingham#4]
Treat cygwin like linux, because its ps command is limited and the proc file system works.

```
 src/shellingham/posix/__init__.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/shellingham/posix/__init__.py b/src/shellingham/posix/__init__.py
index ec27b3a..1f4b80c 100644
--- a/src/shellingham/posix/__init__.py
+++ b/src/shellingham/posix/__init__.py
@@ -6,7 +6,7 @@ from .._consts import SHELL_NAMES
 
 def _get_process_mapping():
     system = platform.system()
-    if system == 'Linux':
+    if system in ('Linux', 'CYGWIN_NT-6.1'):
         from . import linux as impl
     else:
         from . import _default as impl
```

I think the "6.1" string may change a couple times a year. It may be better to do:
```
if system == 'Linux' or system.startswith('CYGWIN_NT'):
```

**Comment by badboybeyer** [comment]
It looks like the BSD4.4 children use `/proc/$PID/status` instead of `/proc/$PID/stat`.

[old openbsd man page](https://man.openbsd.org/OpenBSD-2.8/mount_procfs.8)

[modern freebsd manpage](https://man.openbsd.org/FreeBSD-11.1/procfs.5)

Maybe write the module to:
 ```
try:
    proc()
except:
    ps()
```

**Comment by uranusjr** [comment]
Urrgh! Yeah I guess I need to revise the logic. A try-except is a good idea (but probably not a bare one).

**Comment by uranusjr** [comment]
Okay I think we have two. What’s the third /facepalm

**Comment by uranusjr** [comment]
I decided to

1. Try /proc (detect if it is Linux and BSD styles)
2. If that fails, try ps
3. If ps also fails, raise an error

We can add compatibility to more uncommon formats when someone actually wants them.
