### ISSUE TITLE
Officially support Python 3.7+

### ISSUE THREAD

**Issue by JeppeKlitgaard** [sarugaku/shellingham#47]
Currently Python 3.6 is the most recent supported version according to the classifiers specified in `setup.cfg`.

Python 3.6 is due to lose support later this year and most will probably have migrated to Python 3.8 or 3.9 at this point.

As far as I can tell `shellingham` works perfectly fine on these more recent Python versions - it might be worthwhile to make the classifiers reflect this and perhaps set up a Python version test matrix on CI?

**Comment by uranusjr** [comment]
Absolutely! A pull request would be very welcomed.

**Comment by JeppeKlitgaard** [comment]
I'll gladly put something together, though I am not entirely sure how to implement the test matrix on Github Actions. 

Thanks for getting back to me so quickly!

**Comment by JeppeKlitgaard** [comment]
@uranusjr would you consider removing support for old Python versions, or would you prefer to keep support for Python 2?

The following versions have reached end of life:

* Python 2.6
* Python 2.7
* Python 3.4
* Python 3.5

(see also: https://endoflife.date/python)
