### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ofek** [sarugaku/shellingham#57]
Hello! Any chance we could get a release soon? I'm interested in https://github.com/sarugaku/shellingham/pull/56

cc @uranusjr

**Comment by efugier** [comment]
Same here, up

**Comment by efugier** [comment]
:point_up: poetry support depends on it @uranusjr please make a release :slightly_smiling_face:

**Comment by efugier** [comment]
@techalchemy @frostming maybe?

**Comment by frostming** [comment]
I will do it, thanks

**Comment by ofek** [comment]
@frostming fyi https://github.com/sarugaku/shellingham/pull/59

**Comment by frostming** [comment]
Resolved by #60

**Comment by efugier** [comment]
Thanks a lot @frostming 🙂
