### ISSUE TITLE
[1.5.0] Please Yank 1.5.0 and Release 1.5.1 for Limit package installation to Python >= 3.7

### ISSUE THREAD

**Issue by hswong3i** [sarugaku/shellingham#64]
@uranusjr as #62 follow up, could we Yank 1.5.0 from PyPI and release 1.5.1? Seem not much out standing PR waiting for merge before 1.5.1?

**Comment by hswong3i** [comment]
@uranusjr https://github.com/sarugaku/shellingham/commit/eb61246a54756dde780dcabcd38f10cd7cd0b086 get committed since 2022-08-09, could we have a new release for it accordingly?

**Comment by uranusjr** [comment]
I released 1.5.0.post1 with the change.
