### ISSUE TITLE
unsupported proc format

### ISSUE THREAD

**Issue by dnlserrano** [sarugaku/shellingham#78]
Running an **Apple M1 Pro**, I started to get 

> unsupported proc format

as part of running `poetry shell`

Upon digging, I found this library and saw fairly recent updates. After downgrading from 1.5.2 to 1.5.0, issues is gone.

Have you maybe introduced a regression for M1s?

**Comment by alsyia** [comment]
We're observing that same issue on Intel Mac devices. It bubbles up through Poetry, breaking some of its functions. 

@uranusjr I could look into a PR, but I'm not sure what the fix would be as neither of this file apparently exist on Macs?

**Comment by OnurErgin** [comment]
I confirm this bug too.

The bug is in the proc.py:30

```
    for name in ("stat", "status"):
        if os.path.exists(os.path.join("/proc", str(pid), name)):
            return name
    raise ProcFormatError("unsupported proc format")
```
    
Since MacOS systems do not contain a "/proc" file system, the script is always raising the error.

**Comment by sneakers-the-rat** [comment]
fixed this - https://github.com/sarugaku/shellingham/pull/79

**Comment by uranusjr** [comment]
1.5.3 has been released.

**Comment by dnlserrano** [comment]
Thanks for the very speedy fix folks! ❤️
