### ISSUE TITLE
Configure Pypi trusted publishing pipeline

### ISSUE THREAD

**Issue by michaelfeil** [sarugaku/shellingham#84]
When looking at this repo, I found that it has:
- like 0.5B Downloads and Pypi
- no trusted_publishing pipeline

Would it make sense to introduce one - I'll not enumerate the benefits, assuming they are known for the benefits and don't want to expose how to get the PYPI Token from the CI.

https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
https://docs.pypi.org/trusted-publishers/

**Comment by uranusjr** [comment]
Mind contributing some configurations to kick start this?
